### ISSUE TITLE
Tracker: more hands-off setup

### ISSUE THREAD

**Issue by ethanuppal** [ethanuppal/spade.nvim#6]
- [x] No manual `:TSInstall`
- [x] Research how to use lazy `opt` over a config function calling `setup`
- [x] Research if lazy can encode dependencies in the plugin.
